// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parking.gRPC.Data;

#nullable disable

namespace Parking.gRPC.Migrations
{
    [DbContext(typeof(ParkingContext))]
    partial class ParkingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("Parking.gRPC.Models.PrecoBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorHoraAdicional")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorHoraInicial")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PrecosBase");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ab82400c-427d-4fa3-b190-6c2e9ffb380d"),
                            DataFim = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInicio = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValorHoraAdicional = 1.00m,
                            ValorHoraInicial = 2.00m
                        },
                        new
                        {
                            Id = new Guid("df523227-26c2-4593-9127-5c6da024c622"),
                            DataFim = new DateTime(2023, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInicio = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValorHoraAdicional = 0.75m,
                            ValorHoraInicial = 1.50m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
