version: '3.4'

services:
  parking.api:
    image: ${DOCKER_REGISTRY-}parkingapi
    build:
      context: .
      dockerfile: Services/Parking/Parking.API/Dockerfile
      
  parking.grpc:
    image: ${DOCKER_REGISTRY-}parkinggrpc
    build:
      context: .
      dockerfile: Services/Parking/Parking.gRPC/Dockerfile

  parking.ui:
    image: ${DOCKER_REGISTRY-}parkingui
    build:
      context: .
      dockerfile: UI/Parking/Parking.UI/Dockerfile

